# Generated by Django 4.2.4 on 2024-01-31 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('melotus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('acousticness', models.FloatField(default=0)),
                ('danceability', models.FloatField(default=0)),
                ('energy', models.FloatField(default=0)),
                ('instrumentalness', models.FloatField(default=0)),
                ('liveness', models.FloatField(default=0)),
                ('loudness', models.FloatField(default=0)),
                ('mode', models.FloatField(default=0)),
                ('speechiness', models.FloatField(default=0)),
                ('tempo', models.FloatField(default=0)),
                ('valence', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='melotus_data',
            fields=[
                ('melotus_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melotus.history')),
            ],
        ),
    ]
