# Generated by Django 5.0 on 2024-01-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melotus', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_status',
            name='acousticness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='music_status',
            name='danceability',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='music_status',
            name='energy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='music_status',
            name='instrumentalness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='music_status',
            name='liveness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='music_status',
            name='loudness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='music_status',
            name='mode',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='music_status',
            name='speechiness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='music_status',
            name='tempo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='music_status',
            name='valence',
            field=models.FloatField(default=0),
        ),
    ]
