# Generated by Django 4.2.4 on 2024-02-01 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('melotus', '0002_history_melotus_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='spotify_data',
            fields=[
                ('spotify_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='melotus_data',
            name='spotify_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='melotus.spotify_data'),
        ),
    ]
